ProjectZayShop/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectZayShop.DAL;
using ProjectZayShop.DTOs;
using ProjectZayShop.DTOs.CategoryDtos;
using ProjectZayShop.DTOs.SliderDtos;
using ProjectZayShop.Extensions;
using ProjectZayShop.Models;

namespace ProjectZayShop.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class CategoryController : Controller
	{
		private readonly AppDbContext _context;
		private readonly IWebHostEnvironment _env;

		public CategoryController(AppDbContext context, IWebHostEnvironment env)
		{
			_context = context;
			_env = env;
		}

		public IActionResult Index()
		{
			IQueryable<Category> categories = _context.Categories;
			GetAllDto<CategoryGetDto> getAllDto = new();
			getAllDto.Items = categories.Select(x => new CategoryGetDto
			{
				Id = x.Id,
				Name = x.Name,
				Image = x.Image,
			}).ToList();
			return View(getAllDto.Items);
		}

		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		public IActionResult Create(CategoryPostDto categoryPostDto)
		{
			_context.Categories.Add(new Category
			{
				Name = categoryPostDto.Name,
				Image = categoryPostDto.File.CreateImage(_env.WebRootPath,"assets/img"),
			});
			_context.SaveChanges();
			return RedirectToAction(nameof(Index));
		}

		public IActionResult Update(int Id)
		{
			Category category = _context.Categories.Find(Id);
			CategoryUpdateDto categoryUpdateDto = new CategoryUpdateDto()
			{
				categoryGetDto = new CategoryGetDto() { Id = category.Id, Name = category.Name, Image = category.Image }
			};
			return View(categoryUpdateDto);
		}

		[HttpPost]
		public IActionResult Update(CategoryUpdateDto categoryUpdateDto)
		{
			Category category = _context.Categories.Find(categoryUpdateDto.categoryGetDto.Id);
			category.Name = categoryUpdateDto.categoryPostDto.Name;
			if(categoryUpdateDto.categoryPostDto.File!= null)
			{
				category.Image=categoryUpdateDto.categoryPostDto.File.CreateImage(_env.WebRootPath,"assets/img");
			}
			_context.SaveChanges();
			return RedirectToAction(nameof(Index));
		}
		public IActionResult Delete(int Id)
		{
			Category category = _context.Categories.Find(Id);
			_context.Categories.Remove(category);
			_context.SaveChanges();
			return RedirectToAction(nameof(Index));
		}
	}
}

ProjectZayShop/Areas/Admin/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProjectZayShop.DAL;
using ProjectZayShop.DTOs;
using ProjectZayShop.DTOs.ProductDtos;
using ProjectZayShop.Extensions;
using ProjectZayShop.Models;
namespace ProjectZayShop.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class ProductController : Controller
	{
		private readonly AppDbContext _context;
		private readonly IMapper _mapper;
		private readonly IWebHostEnvironment _env;

        public object ProductUpdateDto { get; private set; }

        public ProductController(AppDbContext context, IMapper mapper, IWebHostEnvironment env)
		{
			_context = context;
			_mapper = mapper;
			_env = env;
		}

		public IActionResult Index()
		{
			IQueryable<Product> products = _context.Products;
			GetAllDto<ProductGetDto> getAllDto = new();
			getAllDto.Items = products.Select(x => new ProductGetDto
			{
				Id = x.Id,
				Name = x.Name,
				Price = x.Price,
				Description	= x.Description,
				Category= x.Category,
				Image= x.Image
				
			}).ToList();
			return View(getAllDto.Items);
		}

		public IActionResult Create()
		{
			ViewBag.Categories = _context.Categories.ToList();
			return View();
		}

		[HttpPost]
		public IActionResult Create(ProductPostDto productPostDto)
		{
			ViewBag.Categories=_context.Categories.ToList();
			Product product=_mapper.Map<Product>(productPostDto);
			product.Image = productPostDto.File.CreateImage(_env.WebRootPath, "assets/img");
			if(product.Image is null)
			{
				ModelState.AddModelError("", "Can't be null");
				return View();
			}
			_context.Products.Add(product);
			_context.SaveChanges();
			return RedirectToAction(nameof(Index));
		}

		public IActionResult Update(int Id)
		{
			Product product = _context.Products.Find(Id);
			ProductUpdateDto
			return View();
		}
	}
}

ProjectZayShop/Areas/Admin/Controllers/SliderController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProjectZayShop.DAL;
using ProjectZayShop.DTOs;
using ProjectZayShop.DTOs.SliderDtos;
using ProjectZayShop.Extensions;
using ProjectZayShop.Models;
using System.Reflection.Metadata;

namespace ProjectZayShop.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class SliderController : Controller
	{
		private readonly AppDbContext _context;
		private readonly IMapper _mapper;
		private readonly IWebHostEnvironment _environment;

        public SliderController(AppDbContext context, IMapper mapper,IWebHostEnvironment environment)
        {
            _context = context;
            _mapper = mapper;
            _environment = environment;
        }

        public IActionResult Index()
		{
            IQueryable<Slider> sliders = _context.Sliders;
            GetAllDto<SliderGetDto> getAllDto = new();
            getAllDto.Items = sliders.Select(x => new SliderGetDto
            {
                Id = x.Id,
                Name = x.Name,
                Slogan = x.Slogan,
                Description = x.Description,
                ImageName = x.ImageName,
            }).ToList();
            return View(getAllDto.Items);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
		public IActionResult Create(SliderPostDto sliderPostDto)
        {
            
            _context.Sliders.Add(new Slider
            {
                Name = sliderPostDto.Name,
                Slogan = sliderPostDto.Slogan,
                Description = sliderPostDto.Description,
                ImageName = sliderPostDto.File.CreateImage(_environment.WebRootPath,"assets/img")
            });
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int Id)
        {
            Slider slider = _context.Sliders.Find(Id);
            SliderUpdateDto sliderUpdateDto = new SliderUpdateDto()
            {
                sliderGetDto = new SliderGetDto()
                {
                    Id=slider.Id,
                    Name = slider.Name,
                    Slogan = slider.Slogan,
                    Description = slider.Description
                }
            };
            return View(sliderUpdateDto);
        }

        [HttpPost]
        public IActionResult Update(SliderUpdateDto sliderUpdateDto)
        {
            Slider slider = _context.Sliders.Find(sliderUpdateDto.sliderGetDto.Id);
            slider.Name=sliderUpdateDto.sliderPostDto.Name;
            slider.Slogan = sliderUpdateDto.sliderPostDto.Slogan;
            slider.Description = sliderUpdateDto.sliderPostDto.Description;
            if(sliderUpdateDto.sliderGetDto.ImageName!=null)
            {
                slider.ImageName = sliderUpdateDto.sliderPostDto.File.CreateImage(_environment.WebRootPath, "assets/img");
            }
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int Id)
        {
			Slider slider = _context.Sliders.Find(Id);
            _context.Sliders.Remove(slider);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
		}



        
    }

}

ProjectZayShop/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>DarkPan - Bootstrap 5 Admin Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/admin/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/admin/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/admin/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/admin/css/style.css" rel="stylesheet">
</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href="index.html" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-user-edit me-2"></i>DarkPan</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="~/admin/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">Jhon Doe</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="index.html" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Elements</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="button.html" class="dropdown-item">Buttons</a>
                            <a asp-area="Admin" asp-controller="Slider" asp-action="Index" class="dropdown-item">Sliders</a>
                            <a href="element.html" class="dropdown-item">Other Elements</a>
                        </div>
                    </div>
                    <a asp-area="Admin" asp-controller="Category" asp-action="Index" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Category</a>
                    <a asp-area="Admin" asp-controller="Product" asp-action="Index" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Products</a>
                    <a href="table.html" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Tables</a>
                    <a href="chart.html" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>Charts</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>Pages</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="signin.html" class="dropdown-item">Sign In</a>
                            <a href="signup.html" class="dropdown-item">Sign Up</a>
                            <a href="404.html" class="dropdown-item">404 Error</a>
                            <a href="blank.html" class="dropdown-item">Blank Page</a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->
        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <form class="d-none d-md-flex ms-4">
                    <input class="form-control bg-dark border-0" type="search" placeholder="Search">
                </form>
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-envelope me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Message</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="~/admin/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="~/admin/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="~/admin/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all message</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-bell me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Notificatin</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Profile updated</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">New user added</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Password changed</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all notifications</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="~/admin/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex">John Doe</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Settings</a>
                            <a href="#" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->

    <div>
        @RenderBody()
                <!-- Footer Start -->
                <div class="container-fluid pt-4 px-4">
                    <div class="bg-secondary rounded-top p-4">
                        <div class="row">
                            <div class="col-12 col-sm-6 text-center text-sm-start">
                                &copy; <a href="#">Your Site Name</a>, All Right Reserved.
                            </div>
                            <div class="col-12 col-sm-6 text-center text-sm-end">
                                <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                                Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                                <br>Distributed By: <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Footer End -->
            </div>
            <!-- Content End -->
            <!-- Back to Top -->
            <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
        </div>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/admin/lib/chart/chart.min.js"></script>
        <script src="~/admin/lib/easing/easing.min.js"></script>
        <script src="~/admin/lib/waypoints/waypoints.min.js"></script>
        <script src="~/admin/lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="~/admin/lib/tempusdominus/js/moment.min.js"></script>
        <script src="~/admin/lib/tempusdominus/js/moment-timezone.min.js"></script>
        <script src="~/admin/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

        <!-- Template Javascript -->
        <script src="~/admin/js/main.js"></script>
</body>